name: auto_factory
description: Compile time factory generator
version: 0.1.0-dev.1
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  path: ^1.7.0
  analyzer: ^0.39.8
  build: ^1.2.2
  source_gen: ^0.9.5
  meta: ^1.1.8

dev_dependencies:
  build_runner: ^1.9.0
  source_gen_test: ^0.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
