name: auto_factory_annotation
description: >-
  Automatically generate code for creating objects 
  and their dependecies through factory classes. This is the annotation part
version: 1.1.0
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  pedantic: ^1.11.0
