name: auto_factory_annotation
description: >-
  Classes that support factory code generation via the
  `auto_factory` package.
version: 0.1.0-dev.1
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: '>=2.7.0 <3.0.0'
