name: auto_factory
description: >-
  Automatically generate code for creating objects 
  and their dependecies through factory classes
version: 1.0.0+2
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  source_gen: ^0.9.10+4
  auto_factory_annotation: ^1.0.0+1
  path: ^1.8.0
  build: ^2.0.0
  analyzer: ">0.0.0 <2.0.0"

dev_dependencies:
  build_runner:
  source_gen_test:
  test: ^1.16.5
  pedantic: ^1.11.0
