name: auto_factory
description: >-
  Automatically generate code for creating objects 
  and their dependecies through factory classes
version: 2.3.0
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  source_gen: ^1.0.0
  build: ^2.0.0
  analyzer: ^5.12.0
  auto_factory_annotation: ^2.1.1
  path: ^1.8.0
 
dev_dependencies:
  source_gen_test: ^1.0.0
  test: ^1.16.8
  lints: ^2.1.0
  build_runner:
