name: auto_factory
description: >-
  Automatically generate code for creating object 
  and their dependecies throug factory classes
version: 0.1.4
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  auto_factory_annotation: ^0.1.0
  path: ^1.7.0
  build: ^1.3.0
  source_gen: ^0.9.5
  meta: ^1.1.8
  analyzer: ^0.39.8
  built_value: ^7.1.0

dev_dependencies:
  build_runner:
  source_gen_test: ^0.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
  built_value_generator: ^7.1.0
