name: auto_factory
description: >-
  Automatically generate code for creating object 
  and their dependecies throug factory classes
version: 0.1.3
homepage: https://github.com/msiviero/dart.auto-factory

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  auto_factory_annotation: ^0.1.0
  path: ^1.7.0
  build: ^1.6.1
  source_gen: ^0.9.10+1
  meta: ^1.1.8
  analyzer: 

dev_dependencies:
  build_runner: ^1.10.12
  source_gen_test: ^0.1.1
  pedantic: ^1.8.0
  test: ^1.6.0
